---
title: "Geomatics Technologies for Enhanced Plant Protection Product Efficacy Evaluation"
subtitle: "Integrating Spatial Data with Geostatistical Methods"
author: "Samuele Bumbaca"
institute: "University of Turin"
date: "July 17, 2025"
theme: "Madrid"
colortheme: "default"
fonttheme: "structurebold"
aspectratio: 169
navigation: horizontal
toc: true
slide_level: 2
header-includes:
  - \usepackage{graphicx}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---

# Presentation Configuration

This file contains the configuration for converting the Markdown presentation to various formats using Pandoc or similar tools.

## Usage Examples

### Convert to PDF (Beamer)
```bash
pandoc PhD_Thesis_Presentation.md -t beamer -o presentation.pdf --slide-level=2
```

### Convert to HTML (reveal.js)
```bash
pandoc PhD_Thesis_Presentation.md -t revealjs -s -o presentation.html
```

### Convert to PowerPoint
```bash
pandoc PhD_Thesis_Presentation.md -t pptx -o presentation.pptx
```

## Timing Guidelines

- **Total Duration**: 40 minutes
- **Average per slide**: 30-60 seconds
- **Introduction section**: ~30 seconds per slide
- **Technical sections**: ~45 seconds per slide
- **Conclusion section**: ~30 seconds per slide

## Presentation Notes

### Key Points to Emphasize
1. **Problem significance**: Current limitations in agricultural statistics
2. **Innovation**: First systematic evaluation of geomatics in EPPO framework
3. **Practical impact**: Ready for regulatory adoption
4. **Scientific rigor**: All methods meet/exceed EPPO benchmarks

### Potential Questions to Prepare
1. Computational requirements and scalability
2. Cost-benefit analysis of implementation
3. Regulatory acceptance timeline
4. Comparison with existing commercial solutions
5. Generalization to other crops and regions
